hydra:
  job:
    chdir: false

Hyperparameters:
  Epoch: 5
  Batch_Size: 16
  learning_rate: 1e-05
  seed: 8

Data:
  train:
    filepath: "data/processed_data/train.csv"
  valid:
    filepath: "data/processed_data/valid.csv"
